env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
  - html
overrides: []
globals:
  Webtie: writeable
parserOptions:
  ecmaVersion: latest
rules:
  prettier/prettier: error
